# Site settings
baseurl = "https://imui.org/"
languageCode = "de"
DefaultContentLanguage = "de"

[languages]
    [languages.de]
        title = "imui e.V."
    [languages.en]
        title = "imui org"

[params]
	name = "Your name"
	description = "Your description"
	email = "info@imui.org"

	[params.header]
		title = "imui"
		shortBio = "Verein für inklusive Musikinstrumente"

	[params.about]
		title = "Über uns"
		bio = "Klänge erleben und auslösen - Teilhabe an und durch Musik für jeden, auch für Menschen die sonst nur eingeschränkt oder erschwert diese Möglichkeit haben - das ist die Vision von imui e.V. Dafür entwickeln wir barrierefreie, digitale Musikinstrumente."

    [params.donation]
        title = "Spenden"

    [params.donators]
        title = "Partner/Förderer"
	# Contact secion
	[params.contact]
		title = "Kontakt"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "github"
			link = "//github.com/imui-org"

	[params.form]
		title = "Kontaktformular"
		# Form fields
		name = "Name"
		email = "Email-Addresse"
		message = "Nachricht"
		buttonText = "Senden"


	[params.footer]
		copyright = "Copyright (C) 2020 imui e.V."
