# Site settings
baseurl = "https://example.org/"
languageCode = "de"
title = "imui e.V."

[params]
	name = "Your name"
	description = "Your description"
	email = "info@imui.org"

	[params.header]
		title = "imui"
		shortBio = "Verein für inklusive Musikinstrumente"

	[params.about]
		title = "Über uns"
		bio = "Klänge erleben und auslösen - Teilhabe an und durch Musik für jeden, auch für Menschen die sonst nur eingeschränkt oder erschwert diese Möglichkeit haben - das ist die Vision von imui e.V. Dafür entwickeln wir barrierefreie, digitale Musikinstrumente."

	# Contact secion
	[params.contact]
		title = "Kontakt"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "github"
			link = "//github.com/imui-e-V"

	[params.form]
		title = "Let's work together"
		# Form fields
		name = "Name"
		email = "Email-Addresse"
		message = "Tell me about your project"
		buttonText = "Send"


	[params.footer]
		copyright = "Published under the Unlicense License."
